static int tolua_Singularity_scripting_Singularity_Scripting_LuaNetworkDelegate_new00(lua_State* tolua_S)
{
	unsigned funcRef;
	tolua_Error tolua_err;
	Singularity::Scripting::LuaNetworkDelegate* tolua_ret;

	if(!tolua_isusertable(tolua_S,1,"Singularity::Scripting::LuaNetworkDelegate",0,&tolua_err) || !tolua_isnoobj(tolua_S,3,&tolua_err) || !lua_isfunction(tolua_S,2))
		goto tolua_lerror;

	funcRef = lua_ref(tolua_S, 2);

	tolua_ret = (Singularity::Scripting::LuaNetworkDelegate*) Mtolua_new((Singularity::Scripting::LuaNetworkDelegate)(funcRef));
	tolua_pushusertype(tolua_S, (void*)tolua_ret, "Singularity::Scripting::LuaNetworkDelegate");
	return 1;

	tolua_lerror:
	tolua_error(tolua_S,"#ferror in function 'new'.",&tolua_err);
	return 0;
};

static int tolua_Singularity_scripting_Singularity_Scripting_LuaCollisionDelegate_new00(lua_State* tolua_S)
{
	unsigned funcRef;
	tolua_Error tolua_err;
	Singularity::Scripting::LuaCollisionDelegate* tolua_ret;

	if(!tolua_isusertable(tolua_S,1,"Singularity::Scripting::LuaCollisionDelegate",0,&tolua_err) || !tolua_isnoobj(tolua_S,3,&tolua_err) || !lua_isfunction(tolua_S,2))
		goto tolua_lerror;

	funcRef = lua_ref(tolua_S, 2);

	tolua_ret = (Singularity::Scripting::LuaCollisionDelegate*) Mtolua_new((Singularity::Scripting::LuaCollisionDelegate)(funcRef));
	tolua_pushusertype(tolua_S, (void*)tolua_ret, "Singularity::Scripting::LuaCollisionDelegate");
	return 1;

	tolua_lerror:
	tolua_error(tolua_S,"#ferror in function 'new'.",&tolua_err);
	return 0;
};

static int tolua_Singularity_scripting_Singularity_Scripting_LuaListBoxDelegate_new00(lua_State* tolua_S)
{
	unsigned funcRef;
	tolua_Error tolua_err;
	Singularity::Scripting::LuaListBoxDelegate* tolua_ret;

	if(!tolua_isusertable(tolua_S,1,"Singularity::Scripting::LuaListBoxDelegate",0,&tolua_err) || !tolua_isnoobj(tolua_S,3,&tolua_err) || !lua_isfunction(tolua_S,2))
		goto tolua_lerror;

	funcRef = lua_ref(tolua_S, 2);

	tolua_ret = (Singularity::Scripting::LuaListBoxDelegate*) Mtolua_new((Singularity::Scripting::LuaListBoxDelegate)(funcRef));
	tolua_pushusertype(tolua_S, (void*)tolua_ret, "Singularity::Scripting::LuaListBoxDelegate");
	return 1;

	tolua_lerror:
	tolua_error(tolua_S,"#ferror in function 'new'.",&tolua_err);
	return 0;
};

static int tolua_Singularity_scripting_Singularity_Scripting_LuaControlKeyboardDelegate_new00(lua_State* tolua_S)
{
	unsigned funcRef;
	tolua_Error tolua_err;
	Singularity::Scripting::LuaControlKeyboardDelegate* tolua_ret;

	if(!tolua_isusertable(tolua_S,1,"Singularity::Scripting::LuaControlKeyboardDelegate",0,&tolua_err) || !tolua_isnoobj(tolua_S,3,&tolua_err) || !lua_isfunction(tolua_S,2))
		goto tolua_lerror;

	funcRef = lua_ref(tolua_S, 2);

	tolua_ret = (Singularity::Scripting::LuaControlKeyboardDelegate*) Mtolua_new((Singularity::Scripting::LuaControlKeyboardDelegate)(funcRef));
	tolua_pushusertype(tolua_S, (void*)tolua_ret, "Singularity::Scripting::LuaControlKeyboardDelegate");
	return 1;

	tolua_lerror:
	tolua_error(tolua_S,"#ferror in function 'new'.",&tolua_err);
	return 0;
};

static int tolua_Singularity_scripting_Singularity_Scripting_LuaControlMouseDelegate_new00(lua_State* tolua_S)
{
	unsigned funcRef;
	tolua_Error tolua_err;
	Singularity::Scripting::LuaControlMouseDelegate* tolua_ret;

	if(!tolua_isusertable(tolua_S,1,"Singularity::Scripting::LuaControlMouseDelegate",0,&tolua_err) || !tolua_isnoobj(tolua_S,3,&tolua_err) || !lua_isfunction(tolua_S,2))
		goto tolua_lerror;

	funcRef = lua_ref(tolua_S, 2);

	tolua_ret = (Singularity::Scripting::LuaControlMouseDelegate*) Mtolua_new((Singularity::Scripting::LuaControlMouseDelegate)(funcRef));
	tolua_pushusertype(tolua_S, (void*)tolua_ret, "Singularity::Scripting::LuaControlMouseDelegate");
	return 1;

	tolua_lerror:
	tolua_error(tolua_S,"#ferror in function 'new'.",&tolua_err);
	return 0;
};

static int tolua_Singularity_scripting_Singularity_Scripting_LuaControlDelegate_new00(lua_State* tolua_S)
{
	unsigned funcRef;
	tolua_Error tolua_err;
	Singularity::Scripting::LuaControlDelegate* tolua_ret;

	if(!tolua_isusertable(tolua_S,1,"Singularity::Scripting::LuaControlDelegate",0,&tolua_err) || !tolua_isnoobj(tolua_S,3,&tolua_err) || !lua_isfunction(tolua_S,2))
		goto tolua_lerror;

	funcRef = lua_ref(tolua_S, 2);

	tolua_ret = (Singularity::Scripting::LuaControlDelegate*) Mtolua_new((Singularity::Scripting::LuaControlDelegate)(funcRef));
	tolua_pushusertype(tolua_S, (void*)tolua_ret, "Singularity::Scripting::LuaControlDelegate");
	return 1;

	tolua_lerror:
	tolua_error(tolua_S,"#ferror in function 'new'.",&tolua_err);
	return 0;
};

static int tolua_Singularity_scripting_Singularity_Scripting_LuaTransformDelegate_new00(lua_State* tolua_S)
{
	unsigned funcRef;
	tolua_Error tolua_err;
	Singularity::Scripting::LuaTransformDelegate* tolua_ret;

	if(!tolua_isusertable(tolua_S,1,"Singularity::Scripting::LuaTransformDelegate",0,&tolua_err) || !tolua_isnoobj(tolua_S,3,&tolua_err) || !lua_isfunction(tolua_S,2))
		goto tolua_lerror;

	funcRef = lua_ref(tolua_S, 2);

	tolua_ret = (Singularity::Scripting::LuaTransformDelegate*) Mtolua_new((Singularity::Scripting::LuaTransformDelegate)(funcRef));
	tolua_pushusertype(tolua_S, (void*)tolua_ret, "Singularity::Scripting::LuaTransformDelegate");
	return 1;

	tolua_lerror:
	tolua_error(tolua_S,"#ferror in function 'new'.",&tolua_err);
	return 0;
};

static int tolua_Singularity_scripting_Singularity_Scripting_LuaBehaviorDelegate_new00(lua_State* tolua_S)
{
	unsigned funcRef;
	tolua_Error tolua_err;
	Singularity::Scripting::LuaBehaviorDelegate* tolua_ret;

	if(!tolua_isusertable(tolua_S,1,"Singularity::Scripting::LuaBehaviorDelegate",0,&tolua_err) || !tolua_isnoobj(tolua_S,3,&tolua_err) || !lua_isfunction(tolua_S,2))
		goto tolua_lerror;

	funcRef = lua_ref(tolua_S, 2);

	tolua_ret = (Singularity::Scripting::LuaBehaviorDelegate*) Mtolua_new((Singularity::Scripting::LuaBehaviorDelegate)(funcRef));
	tolua_pushusertype(tolua_S, (void*)tolua_ret, "Singularity::Scripting::LuaBehaviorDelegate");
	return 1;

	tolua_lerror:
	tolua_error(tolua_S,"#ferror in function 'new'.",&tolua_err);
	return 0;
};

static int tolua_Singularity_scripting_Singularity_Physics_Collider_SphereCast00(lua_State* tolua_S)
{
	Vector3 centerpoint = *((Vector3*)  tolua_tousertype(tolua_S,1,0));
	float radius = ((float)  tolua_tonumber(tolua_S,2,0));
	int count = ((int)  tolua_tonumber(tolua_S,3,0));
	{
		DynamicList<Singularity::Physics::Collider*> colliders = Singularity::Physics::Collider::SphereCast(centerpoint,radius,count);
		
		lua_newtable(tolua_S);
		int top = lua_gettop(tolua_S);

		for (int i = 0; i < count; ++i)
		{
			tolua_pushnumber(tolua_S, i);
			tolua_pushusertype(tolua_S, colliders[i], "Singularity::Physics::Collider");
			lua_settable(tolua_S, top);
		}

		tolua_pushnumber(tolua_S,(lua_Number)count);
	}
	return 2;
}

static int tolua_Singularity_scripting_Vector3_Project00(lua_State* tolua_S)
{
	Matrix world;
	D3D10_VIEWPORT viewport;
	tolua_Error tolua_err;
	if (!tolua_isusertype(tolua_S,1,"Vector3",0,&tolua_err) ||
		!tolua_isusertype(tolua_S,2,"Singularity::Graphics::Camera",0,&tolua_err) ||
		!tolua_isnoobj(tolua_S,3,&tolua_err))
		goto tolua_lerror;
	else
	{
		Vector3* tolua_obj = new Vector3(0,0,0);
		Vector3* self = (Vector3*)  tolua_tousertype(tolua_S,1,0);
		Camera* camera = ((Camera*)  tolua_tousertype(tolua_S,2,0));

		Matrix view = camera->Get_View();
		Matrix projection = camera->Get_Projection();
		Singularity::Graphics::Devices::HardwareDevice::Instantiate()->GetViewport(viewport.TopLeftX, viewport.TopLeftY, viewport.Width, viewport.Height, viewport.MinDepth, viewport.MaxDepth);

		D3DXVec3Project((D3DXVECTOR3*)tolua_obj, (D3DXVECTOR3*)self, &viewport, (D3DXMATRIX*)&projection, (D3DXMATRIX*)&view, (D3DXMATRIX*)&world);
		
		tolua_pushusertype(tolua_S,tolua_obj,"Vector3");
		tolua_register_gc(tolua_S,lua_gettop(tolua_S));
	}
	
	return 1;

	tolua_lerror:
		tolua_error(tolua_S,"#ferror in function 'Project'.",&tolua_err);
		return 0;
}

static int tolua_Singularity_scripting_Singularity_Networking_Network_FindGames00(lua_State* tolua_S)
{
	tolua_Error tolua_err;
	if (!tolua_isusertable(tolua_S,1,"Singularity::Networking::Network",0,&tolua_err) ||
		!tolua_isnoobj(tolua_S,2,&tolua_err))
		goto tolua_lerror;

	unsigned count;
	Singularity::Networking::NetworkGameDescription* games = Singularity::Networking::Network::FindGames(count);
	
	tolua_pushnumber(tolua_S,(lua_Number)count);
	
	lua_newtable(tolua_S);
	int top = lua_gettop(tolua_S);
	for (unsigned i = 0; i < count; ++i)
	{
		tolua_pushnumber(tolua_S, i+1);
		tolua_pushusertype(tolua_S, &games[i], "Singularity::Networking::NetworkGameDescription");

		lua_settable(tolua_S, top);
	}
	return 2;
 
	tolua_lerror:
		tolua_error(tolua_S,"#ferror in function 'FindGames'.",&tolua_err);
		return 0;
}

static int tolua_Singularity_scripting_Singularity_Networking_NetworkGame_GetPlayers00(lua_State* tolua_S)
{
	tolua_Error tolua_err;
	if (!tolua_isusertype(tolua_S,1,"Singularity::Networking::NetworkGame",0,&tolua_err) ||
		!tolua_isnumber(tolua_S,2,0,&tolua_err) ||
		!tolua_isnoobj(tolua_S,3,&tolua_err))
		goto tolua_lerror;
		

	Singularity::Networking::NetworkGame* self = (Singularity::Networking::NetworkGame*)  tolua_tousertype(tolua_S,1,0);
	unsigned count = ((unsigned)  tolua_tonumber(tolua_S,2,0));
	if (!self) 
		tolua_error(tolua_S,"invalid 'self' in function 'GetPlayers'", NULL);

	Singularity::Networking::NetworkPlayer* players = self->GetPlayers(count);
	tolua_pushnumber(tolua_S,(lua_Number)count);
	
	lua_newtable(tolua_S);
	int top = lua_gettop(tolua_S);
	for (unsigned i = 0; i < count; ++i)
	{
		tolua_pushnumber(tolua_S, i+1);
		tolua_pushusertype(tolua_S, &players[i], "Singularity::Networking::NetworkPlayer");

		lua_settable(tolua_S, top);
	}
	
	return 2;
	
	tolua_lerror:
		tolua_error(tolua_S,"#ferror in function 'GetPlayers'.",&tolua_err);
		return 0;
}