#ifndef SINGULARITY_SCRIPTING_MAX_SUBTASKS
#define SINGULARITY_SCRIPTING_MAX_SUBTASKS 1
#endif

#define TOLUA_DISABLE_tolua_Singularity_scripting_Singularity_Scripting_LuaBehaviorDelegate_new00 1
#define TOLUA_DISABLE_tolua_Singularity_scripting_Singularity_Scripting_LuaTransformDelegate_new00 1
#define TOLUA_DISABLE_tolua_Singularity_scripting_Singularity_Scripting_LuaControlDelegate_new00 1
#define TOLUA_DISABLE_tolua_Singularity_scripting_Singularity_Scripting_LuaControlMouseDelegate_new00 1
#define TOLUA_DISABLE_tolua_Singularity_scripting_Singularity_Scripting_LuaControlKeyboardDelegate_new00 1
#define TOLUA_DISABLE_tolua_Singularity_scripting_Singularity_Scripting_LuaListBoxDelegate_new00 1
#define TOLUA_DISABLE_tolua_Singularity_scripting_Singularity_Scripting_LuaCollisionDelegate_new00 1
#define TOLUA_DISABLE_tolua_Singularity_scripting_Singularity_Scripting_LuaNetworkDelegate_new00 1


#define TOLUA_DISABLE_tolua_Singularity_scripting_Singularity_Physics_Collider_SphereCast00 1
#define TOLUA_DISABLE_tolua_Singularity_scripting_Vector3_Project00 1
#define TOLUA_DISABLE_tolua_Singularity_scripting_Singularity_Networking_Network_FindGames00 1
#define TOLUA_DISABLE_tolua_Singularity_scripting_Singularity_Networking_NetworkGame_GetPlayers00 1

#define Mtolua_delete(EXP) //don't corrupt memory, delete EXP