#ifndef SINGULARITY_NINEPATCH_DEFAULT_CENTER
#define SINGULARITY_NINEPATCH_DEFAULT_CENTER Vector4(0, 0, 0, 0)
#endif

#ifndef SINGULARITY_NINEPATCH_DEFAULT_FILEPATH
#define SINGULARITY_NINEPATCH_DEFAULT_FILEPATH "..\\..\\..\\Assets\\Textures\\Menus\\DefaultGUITexture1.png"
//#define SINGULARITY_NINEPATCH_DEFAULT_FILEPATH "..\\..\\..\\Assets\\Textures\\Gui\\window.ninepath.png"
#endif

#ifndef SINGULARITY_GUI_DEFAULT_FONT_NAME
#define SINGULARITY_GUI_DEFAULT_FONT_NAME "Franklin Gothic11 Bold"
#endif

#ifndef SINGULARITY_GUI_DEFAULT_FONT_FILEPATH
#define SINGULARITY_GUI_DEFAULT_FONT_FILEPATH "..\\..\\..\\Assets\\Fonts\\FranklinGothicBold11.bmp"
#endif

#ifndef SINGULARITY_GUI_DEFAULT_MATERIAL_FILEPATH
#define SINGULARITY_GUI_DEFAULT_MATERIAL_FILEPATH "..\\..\\..\\Assets\\Effects\\shader_guieffect.fx"
#endif

#ifndef SINGULARITY_PANEL_DEFAULT_PADDING
#define SINGULARITY_PANEL_DEFAULT_PADDING 10
#endif

// per CONTROL.
#ifndef SINGULARITY_GUI_TEXT_CHAR_LIMIT
#define SINGULARITY_GUI_TEXT_CHAR_LIMIT 100
#endif

#ifndef SINGULARITY_GUI_DEFAULT_KERNING
#define SINGULARITY_GUI_DEFAULT_KERNING 5
#endif

#ifndef SINGULARITY_GUI_MAX_WINDOW_COUNT
#define SINGULARITY_GUI_MAX_WINDOW_COUNT 20
#endif

#ifndef SINGULARITY_GUI_MAX_LISTBOX_ELEMENT_COUNT
#define SINGULARITY_GUI_MAX_LISTBOX_ELEMENT_COUNT 10
#endif

#ifndef SINGULARITY_GUI_DEPTH_DIFFERENCE
#define SINGULARITY_GUI_DEPTH_DIFFERENCE 0.00001f
#endif