#ifndef SINGULARITY_MAX_BATCHES
#define SINGULARITY_MAX_BATCHES 20
#endif

#ifndef SINGULARITY_MAX_EFFECT_LINK
#define SINGULARITY_MAX_EFFECT_LINK 10
#endif

#ifndef SINGULARITY_RENDERER_MAX_SUBTASKS
#define SINGULARITY_RENDERER_MAX_SUBTASKS 1
#endif

#ifndef SINGULARITY_RENDERER_DEFAULT_BUFFERED_CAPACITY
#define SINGULARITY_RENDERER_DEFAULT_BUFFERED_CAPACITY 100000
#endif