#ifndef SINGULARITY_PARTICLES_DEFAULT_EFFECTPATH
#define SINGULARITY_PARTICLES_DEFAULT_EFFECTPATH "..\\..\\..\\Assets\\Effects\\shader_particles.fx"
#endif

#ifndef SINGULARITY_PARTICLES_MAX_EMITTERS
#define SINGULARITY_PARTICLES_MAX_EMITTERS 1000
#endif